enable non-us-south envs
Signed-off-by: Doug Davis <dug@us.ibm.com>

diff --git a/bin/run-tutorial b/bin/run-tutorial
--- a/bin/run-tutorial
+++ b/bin/run-tutorial
@@ -2,6 +2,7 @@
 
 set -e -o pipefail
 [[ "$1" == "clean" ]] && CLEAN="true"
+[[ "$DRYRUN" != "" ]] && EVAL=":" || EVAL="eval"
 
 while read -u 3 line ; do
   line="$prev$line"
@@ -21,7 +22,8 @@ while read -u 3 line ; do
 
     if [[ "$CLEAN" == "" || "$FOUND_CLEAN" != "" ]]; then
       env | sort > origenv
-      eval $line || { echo "Failed: $line" ; exit 1 ; }
+      # echo '#' $line
+      $EVAL $line || { echo "Failed: $line" ; exit 1 ; }
       set +e ; env | sort | diff origenv - | grep -v '^[0-9]\+a' ; set -e
       echo
     fi
@@ -30,7 +32,7 @@ while read -u 3 line ; do
       line=${line:2}
       echo -n '$' $line" "
       test -n "$PAUSE" && { read -sn 1 a; [[ "$a" == "r" ]] && PAUSE=""; }; echo
-      eval $line 2>&1 | ( ( [[ "$line" == "export"* ]] && cat ) || tee out )
+      $EVAL $line 2>&1 | ( ( [[ "$line" == "export"* ]] && cat ) || tee out )
       echo
       [[ "$line" == "exit"* ]] && exit 0
     fi
