major cleanup and ping->cron
Signed-off-by: Doug Davis <dug@us.ibm.com>

diff --git a/bin/run-tutorial b/bin/run-tutorial
--- a/bin/run-tutorial
+++ b/bin/run-tutorial
@@ -1,17 +1,27 @@
 #!/bin/bash
 
-# use PAUSE=1 to pause on each command
+# Download the "demoscript" utility if not present locally
+if [[ -e .demoscript ]]; then
+  . .demoscript
+else
+  . <(curl -fs https://raw.githubusercontent.com/duglin/tools/master/demoscript/demoscript)
+fi
 
-set -e -o pipefail
+export RETRYONFAIL=true
+
+set +e -o pipefail
 [[ "$1" == "clean" ]] && CLEAN="true"
-[[ "$DRYRUN" != "" ]] && EVAL=":" || EVAL="eval"
+[[ "$DRYRUN" != "" ]] && EVAL="echo" || EVAL="eval"
+[[ "$DRYRUN" != "" ]] && DOIT="echo" || DOIT="doit"
+
+if [[ -n $CLEAN ]]; then
+  skip=1
+  delay=0
+fi
 
 while read -u 3 line ; do
   line="$prev$line"
-  if [[ "$line" == *"\\" ]]; then
-    prev="${line: -2}"
-    continue
-  fi
+  [[ "$line" == *"\\" ]] && prev="${line: -2}" && continue # join w/next line
   prev=""
 
   # Skip all non-user-commands and comment-commands
@@ -23,53 +33,27 @@ while read -u 3 line ; do
   if [[ "$line" == "<!-- "* ]]; then
     # Comment command
     line=${line:5}
-    line=${line%% -->}
+    line=${line% -->}
 
+	# Stop on start of "clean" commands if we're running a demo
+	[[ "$line" == "clean" && -z "$skip" ]] && exit 0
     # Marks the start of our "clean" commands, so turn off "stop on error"
-    [[ "$line" == "clean" ]] && FOUND_CLEAN="true" && set +e && continue
+    [[ "$line" == "clean" ]] && ignorerc="--ignorerc" && set +e && continue
 
-    if [[ "$CLEAN" == "" || "$FOUND_CLEAN" != "" ]]; then
-      env | sort > origenv
-      # echo '#' $line
-      # $EVAL $line || { echo "Failed: $line" ; exit 1 ; }
-      set +e
+    if [[ -z "$CLEAN" || -n "$ignorerc" ]]; then
+	  [[ -n "$ignorerc" ]] && set +e
       $EVAL $line
-      rc=$?
-      set -e
-      if [[ $rc != "0" && -z $FOUND_CLEAN ]]; then
-        echo "Fail: $line"
-        exit 1
-      fi
-      # $EVAL $line || [[ -n "$FOUND_CLEAN" ]] || { echo "Fail: $line";exit 1 ; }
-      (set +e ; env | sort | diff origenv - | grep -v '^[0-9]\+a'>dif ; exit 0)
-      cat dif ; [[ -s dif ]] && echo ; rm -f dif origenv
+	  [[ $? != "0" && -z "$ignorerc" ]] && echo "Fail: $line" && exit 1
     fi
   else
     # User command
-    if [[ "$CLEAN" == "" || -n "$FOUND_CLEAN" ]]; then
-      line=${line:2}
-      echo -n '$' $line" "
-      test -n "$PAUSE" && { read -sn 1 a; [[ "$a" == "r" ]] && PAUSE=""; }; echo
-      start=$(date +%s)
-      set +e
-      # $EVAL $line 2>&1 | ( ( [[ "$line" == "export"* ]] && cat ) || tee out )
-      if [[ "$line" == "export"* ]]; then
-        $EVAL $line
-        rc=$?
-      else
-        ($EVAL $line) 2>&1 | tee out
-        rc=$?
-      fi
-      set -e
-      if [[ $rc != "0" && -z $FOUND_CLEAN ]]; then
-        echo "Fail: $line"
-        exit 1
-      fi
-      end=$(date +%s)
-      [[ -n $SHOWTIME ]] && echo "# Time: $((end-start))s"
-      echo
+    if [[ -z "$CLEAN" || -n "$ignorerc" ]]; then
+      line=${line:2}   # remove $
+	  $DOIT $ignorerc $line
+	  set +e
+	  [[ $? != "0" ]] && exit 2
       [[ "$line" == "exit"* ]] && exit 0
     fi
   fi
-done  3< README.md
-rm -f out
+done  3< ${FILE:-README.md}
+exit 0
