thumbnail
Signed-off-by: Doug Davis <dug@us.ibm.com>

diff --git a/bind-app/run b/bind-app/run
--- a/bind-app/run
+++ b/bind-app/run
@@ -39,8 +39,8 @@ ibmcloud ce app bind --name ba-app --service-instance ba-db
 curl -fs ${URL} | tee out
 [[ "${PIPESTATUS[0]}" == "0" ]]
 
-if ! grep VCAP_SERVICES out > /dev/null ; then
-  echo "Missing VCAP_SERVICES in App's env vars"
+if ! grep CE_SERVICES out > /dev/null ; then
+  echo "Missing CE_SERVICES in App's env vars"
   exit 1
 fi
 
diff --git a/bind-job/run b/bind-job/run
--- a/bind-job/run
+++ b/bind-job/run
@@ -42,8 +42,8 @@ ibmcloud ce jobrun submit --name myrun --job bj-job --wait
 # Now look at a view of the logs to make sure it worked
 ibmcloud ce jobrun logs --instance myrun-1-0 | tee out
 
-if ! grep VCAP_SERVICES out > /dev/null ; then
-  echo "Missing VCAP_SERVICES in App's env vars"
+if ! grep CE_SERVICES out > /dev/null ; then
+  echo "Missing CE_SERVICES in App's env vars"
   exit 1
 fi
 
